import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600']})

export const metadata = {
  title: 'Gerador de senha | Maycon Vinícius',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="PT-BR">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}